# Site metadata
site_name: Crazyarena Documentation
site_url: https://cybaer-nova.github.io/crazyarena/
repo_url: https://github.com/cybaer-nova/crazyarena
repo_name: crazyarena
#edit_uri: edit/main/docs/
site_author: Francisco Santos
theme: 
  name: material
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: blue
    accent: blue
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
  
  icon:
    logo: material/rocket-launch 
    repo: fontawesome/brands/git-alt
  favicon: images/favicon.png
  # Extra features
  features:
    # ---------------------
    # Navigation
    # ---------------------
    # Search index survives navigation
  - navigation.instant
    # The URL in the address bar is automatically updated with scroll
  - navigation.tracking
    # Top address bar with sections
    #- navigation.tabs
    # Bold level 2 sections in left bar
  - navigation.sections
    # Documents can be directly attached to sections (see https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#section-index-pages)
  #- navigation.indexes
    # Automatic left bar scroll
  - toc.follow
    # Back to top button
  - navigation.top
    # ---------------------
    # Search
    # ---------------------
    # Search suggestions in search button
  - search.suggest
  - search.highlight
    # Allow sharing a search result
  - search.share
  - navigation.footer
  - navigation.path
  - toc.integrate
  - navigation.indexes
  - navigation.expand
markdown_extensions:

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  

plugins:
  - monorepo
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang:
      - en
      - pt
extra:
  # ---------------------
  # Remove the 'made with mkdocs'
  # ---------------------
  generator: false

nav:
  - Introduction: 'index.md'
  - Getting Started:
    - Repository Structure: 'repo_structure.md'
    - Install Guide: 'install_guide.md'
    - Docker Containers: 'docker.md'
  - Examples:
    - Hello World: 
      - CrazyS: 'examples/hello_world/crazys.md'
      - Crazyswarm: 'examples/hello_world/crazyswarm.md'
  - Common Errors: 'common_errors.md'
