"""
# Plotting data from log files

Plots the crazyflie data from logfiles generated by the CybAer version of CrazyS simulator

"""

import matplotlib.pyplot as plt
import matplotlib.cbook as cbook
import numpy as np
#import pandas as pd

logs_folder = '../datalogs/'
datetag = '20240223T143929'
fname_pos = logs_folder + datetag + '_DronePosition.csv'
fname_att = logs_folder + datetag + '_DroneAttitude.csv'
fname_oms = logs_folder + datetag + '_PropellersVelocity.csv'

# data is given in first columns, and last two columns are, respectively, the time in seconds and the nanoseconds
data_pos = np.genfromtxt(fname_pos,delimiter=',')
data_att = np.genfromtxt(fname_att,delimiter=',')
data_oms = np.genfromtxt(fname_oms,delimiter=',')
nk,nvars = np.shape(data_pos)
print('dimensions: ',nk,'x',nvars)

# get time in seconds
t = np.zeros((nk,1))
t = data_pos[:,-2] + data_pos[:,-1]*1e-9
print('t dimensions: ',np.shape(t))

# get data
p = np.zeros((nk,3))
p = data_pos[:,0:3]
lbd = np.zeros((nk,3))
lbd = data_att[:,0:3]
oms = np.zeros((nk,4))
oms = data_oms[:,0:4]
print('p dimensions: ',np.shape(p))
print('lbd dimensions: ',np.shape(lbd))
print('oms dimensions: ',np.shape(oms))

# plot trajectory
fig = plt.figure(1)
ax = fig.add_subplot(projection='3d')
ax.plot(p[:,0], p[:,1], p[:,2])
ax.set_xlabel("x [m]")
ax.set_ylabel("y [m]")
ax.set_zlabel("z [m]")
ax.axis('equal')
ax.set_title("Trajectory")
plt.show(block=False)
plt.savefig(datetag + 'results_pos3d.pdf')

# 3 subplots for position
plt.figure(2)
plt.subplot(311)
plt.plot(t,p[:,0])
ax = plt.gca()
ax.set_ylabel("x [m]")
ax.set_xlabel("t [s]")
plt.subplot(312)
plt.plot(t,p[:,1])
ax = plt.gca()
ax.set_ylabel("y [m]")
ax.set_xlabel("t [s]")
plt.subplot(313)
plt.plot(t,p[:,2])
ax = plt.gca()
ax.set_ylabel("z [m]")
ax.set_xlabel("t [s]")
plt.show(block=False)
plt.savefig(datetag + 'results_pos.pdf')

# 3 subplots for Euler angles
plt.figure(3)
plt.subplot(311)
plt.plot(t,lbd[:,0])
ax = plt.gca()
ax.set_ylabel("$\phi$ [rad]")
ax.set_xlabel("t [s]")
plt.subplot(312)
plt.plot(t,lbd[:,1])
ax = plt.gca()
ax.set_ylabel("$\Theta$  [m]")
ax.set_xlabel("t [s]")
plt.subplot(313)
plt.plot(t,lbd[:,2])
ax = plt.gca()
ax.set_ylabel("$\psi$  [m]")
ax.set_xlabel("t [s]")
plt.show(block=False)
plt.savefig(datetag + 'results_att.pdf')

# motor speeds
plt.figure(4)
plt.subplot(411)
plt.plot(t,oms[:,0])
ax = plt.gca()
ax.set_ylabel("$\omega_1$ [rad/s]")
ax.set_xlabel("t [s]")
plt.subplot(412)
plt.plot(t,oms[:,1])
ax = plt.gca()
ax.set_ylabel("$\omega_2$ [rad/s]")
ax.set_xlabel("t [s]")
plt.subplot(413)
plt.plot(t,oms[:,2])
ax = plt.gca()
ax.set_ylabel("$\omega_3$ [rad/s]")
ax.set_xlabel("t [s]")
plt.subplot(414)
plt.plot(t,oms[:,3])
ax = plt.gca()
ax.set_ylabel("$\omega_4$ [rad/s]")
ax.set_xlabel("t [s]")
plt.show(block=False)
plt.savefig(datetag + 'results_oms.pdf')

plt.show()




